name: DEPLOY_TO_ALIYUN_ECS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 10.x
      - name: Install dependencies
        run: yarn
      - name: Build dist
        run: yarn docz:build
      - name: Sync dist to aliyun ecs
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          DEST_PATH: ${{ secrets.DEST_PATH }}
        run: |
          echo "${SSH_PRIVATE_KEY}" > /tmp/pem
          chmod 400 /tmp/pem
          scp -i /tmp/pem -oStrictHostKeyChecking=no -r -P ${SSH_PORT} .docz/dist/* ${SSH_USER}@${SSH_HOST}:${DEST_PATH}
          rm /tmp/pem
